#!/usr/bin/env python3
"""Clean RealSense cup point clouds inside the calibrated table workspace.

中文说明：在校准后的桌面/工作区内采集 RealSense 点云，去除深度边缘飞点、
桌面平面、近桌面残留和离群点，并对杯子候选 cluster 保存 raw/clean PLY。
该脚本只做感知和调试输出，不移动机器人。

This script is perception-only and does not move the Kinova arm.

Pipeline:
1. Capture one aligned RealSense RGB-D frame.
2. Detect ArUco marker ID 23 and compute T_base_camera.
3. Remove depth-edge pixels before point-cloud generation.
4. Build a base-frame point cloud.
5. Crop by configs/table_workspace.yaml.
6. Remove the table plane.
7. DBSCAN cluster remaining objects.
8. Clean each cluster with statistical and radius outlier removal.
9. Save raw/cleaned debug point clouds for inspection.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np
import open3d as o3d
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from perception.aruco_detector import (  # noqa: E402
    MARKER_LENGTH,
    TARGET_MARKER_ID,
    create_aruco_detector,
    detect_target_marker_pose,
)
from perception.realsense_camera import RealSenseCamera  # noqa: E402
from utils.transform_utils import invert_T  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--fps", type=int, default=15)
    parser.add_argument(
        "--camera-stream-order",
        choices=["color_first", "depth_first", "both"],
        default="color_first",
    )
    parser.add_argument("--camera-start-attempts", type=int, default=3)
    parser.add_argument("--camera-retry-delay", type=float, default=2.0)
    parser.add_argument(
        "--camera-hardware-reset-on-fail",
        action="store_true",
        help="Request a RealSense hardware reset before retrying after the first startup failure.",
    )

    parser.add_argument(
        "--calibration",
        type=Path,
        default=PROJECT_ROOT / "configs" / "real_calibration.yaml",
        help="YAML file containing T_base_marker.",
    )
    parser.add_argument(
        "--table-workspace",
        type=Path,
        default=PROJECT_ROOT / "configs" / "table_workspace.yaml",
        help="YAML generated by scripts/calibrate_table_workspace.py.",
    )

    parser.add_argument("--depth-min", type=float, default=0.05)
    parser.add_argument("--depth-trunc", type=float, default=1.20)
    parser.add_argument("--voxel-size", type=float, default=0.004)
    parser.add_argument("--table-distance-threshold", type=float, default=0.008)
    parser.add_argument(
        "--near-table-clearance",
        type=float,
        default=0.006,
        help="After table removal, discard remaining points within this distance from the fitted table plane.",
    )
    parser.add_argument(
        "--disable-near-table-filter",
        action="store_true",
        help="Do not run the extra near-table residual filter after RANSAC table removal.",
    )
    parser.add_argument("--cluster-eps", type=float, default=0.02)
    parser.add_argument("--cluster-min-points", type=int, default=50)
    parser.add_argument(
        "--min-points",
        type=int,
        default=200,
        help="Discard DBSCAN clusters with fewer than this many raw points before cleaning.",
    )

    parser.add_argument(
        "--disable-depth-edge-filter",
        action="store_true",
        help="Keep depth-edge pixels when generating the point cloud.",
    )
    parser.add_argument(
        "--depth-edge-threshold",
        type=float,
        default=0.02,
        help="Reject pixels whose local depth range is larger than this many meters.",
    )
    parser.add_argument(
        "--depth-edge-kernel",
        type=int,
        default=5,
        help="Odd kernel size used to detect local depth discontinuities.",
    )

    parser.add_argument("--disable-statistical-filter", action="store_true")
    parser.add_argument("--stat-nb-neighbors", type=int, default=40)
    parser.add_argument("--stat-std-ratio", type=float, default=1.0)

    parser.add_argument("--disable-radius-filter", action="store_true")
    parser.add_argument("--radius-nb-points", type=int, default=10)
    parser.add_argument("--radius", type=float, default=0.01)
    parser.add_argument(
        "--post-clean-cluster-eps",
        type=float,
        default=0.018,
        help="After outlier removal, DBSCAN each cluster and keep its largest connected component. Use <=0 to disable.",
    )
    parser.add_argument(
        "--post-clean-cluster-min-points",
        type=int,
        default=20,
        help="Minimum points for post-clean largest-component DBSCAN.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "debug_pointclouds" / "cup_clean",
        help="Directory for saved debug point clouds.",
    )
    return parser.parse_args()


def load_T_base_marker(path: Path) -> np.ndarray:
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    T_base_marker = np.asarray(data["T_base_marker"], dtype=np.float64)
    if T_base_marker.shape != (4, 4):
        raise ValueError("T_base_marker must be 4x4.")
    return T_base_marker


def load_table_workspace(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"Missing table workspace file: {path}\n"
            "Run: python scripts/calibrate_table_workspace.py"
        )
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    workspace = data.get("table_workspace", data)
    polygon = np.asarray(workspace["polygon_base_xy"], dtype=np.float64)
    if polygon.ndim != 2 or polygon.shape[1] != 2 or polygon.shape[0] < 3:
        raise ValueError("polygon_base_xy must be an Nx2 polygon with at least three points.")
    return {
        "polygon_base_xy": polygon,
        "z_min": float(workspace["z_min"]),
        "z_max": float(workspace["z_max"]),
        "path": path,
    }


def make_depth_valid_mask(depth_z16, depth_scale_m, args):
    depth_m = depth_z16.astype(np.float32) * float(depth_scale_m)
    valid = np.isfinite(depth_m) & (depth_m >= args.depth_min) & (depth_m <= args.depth_trunc)

    edge_mask = np.zeros(depth_m.shape, dtype=bool)
    if not args.disable_depth_edge_filter:
        k = max(3, int(args.depth_edge_kernel))
        if k % 2 == 0:
            k += 1

        depth_for_max = np.where(valid, depth_m, 0.0).astype(np.float32)
        depth_for_min = np.where(valid, depth_m, float(args.depth_trunc) + 1.0).astype(np.float32)
        kernel = np.ones((k, k), dtype=np.uint8)
        local_max = cv2.dilate(depth_for_max, kernel)
        local_min = cv2.erode(depth_for_min, kernel)
        local_range = local_max - local_min

        edge_mask = valid & np.isfinite(local_range) & (local_range > float(args.depth_edge_threshold))
        valid = valid & ~edge_mask

    return valid, edge_mask, depth_m


def build_camera_point_cloud(frames, valid_mask, args):
    depth_m = frames.depth_z16.astype(np.float64) * float(frames.depth_scale_m)
    h, w = depth_m.shape

    us, vs = np.meshgrid(np.arange(w), np.arange(h))
    z = depth_m[valid_mask]
    x = (us[valid_mask].astype(np.float64) - frames.camera_matrix[0, 2]) * z / frames.camera_matrix[0, 0]
    y = (vs[valid_mask].astype(np.float64) - frames.camera_matrix[1, 2]) * z / frames.camera_matrix[1, 1]
    points = np.stack([x, y, z], axis=1)

    color_rgb = cv2.cvtColor(frames.color_bgr, cv2.COLOR_BGR2RGB)
    colors = color_rgb[valid_mask].astype(np.float64) / 255.0

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    pcd.colors = o3d.utility.Vector3dVector(colors)
    if args.voxel_size > 0:
        pcd = pcd.voxel_down_sample(args.voxel_size)
    return pcd


def transform_pcd(pcd, T_A_B):
    out = o3d.geometry.PointCloud(pcd)
    out.transform(np.asarray(T_A_B, dtype=np.float64).reshape(4, 4))
    return out


def points_in_polygon_xy(points_xy, polygon_xy):
    polygon = np.asarray(polygon_xy, dtype=np.float32).reshape(-1, 1, 2)
    return np.array(
        [cv2.pointPolygonTest(polygon, (float(p[0]), float(p[1])), False) >= 0 for p in points_xy],
        dtype=bool,
    )


def crop_pcd_by_workspace(pcd_base_full, workspace):
    points = np.asarray(pcd_base_full.points)
    colors = np.asarray(pcd_base_full.colors)

    polygon_mask = points_in_polygon_xy(points[:, :2], workspace["polygon_base_xy"])
    z_mask = (points[:, 2] >= workspace["z_min"]) & (points[:, 2] <= workspace["z_max"])
    mask = polygon_mask & z_mask

    pcd_crop = o3d.geometry.PointCloud()
    pcd_crop.points = o3d.utility.Vector3dVector(points[mask])
    if colors.shape[0] == points.shape[0]:
        pcd_crop.colors = o3d.utility.Vector3dVector(colors[mask])
    return pcd_crop


def remove_table_plane(pcd_base_crop, args):
    if len(pcd_base_crop.points) < 100:
        return pcd_base_crop, None, []
    try:
        plane_model, inliers = pcd_base_crop.segment_plane(
            distance_threshold=args.table_distance_threshold,
            ransac_n=3,
            num_iterations=1000,
        )
        return pcd_base_crop.select_by_index(inliers, invert=True), plane_model, inliers
    except RuntimeError:
        return pcd_base_crop, None, []


def remove_near_table_residuals(pcd, plane_model, args):
    if args.disable_near_table_filter or plane_model is None or args.near_table_clearance <= 0:
        return pcd, 0

    points = np.asarray(pcd.points)
    colors = np.asarray(pcd.colors)
    if len(points) == 0:
        return pcd, 0

    a, b, c, d = [float(v) for v in plane_model]
    normal = np.array([a, b, c], dtype=np.float64)
    distances = np.abs(points @ normal + d) / max(float(np.linalg.norm(normal)), 1e-12)
    keep = distances > float(args.near_table_clearance)

    filtered = o3d.geometry.PointCloud()
    filtered.points = o3d.utility.Vector3dVector(points[keep])
    if colors.shape[0] == points.shape[0]:
        filtered.colors = o3d.utility.Vector3dVector(colors[keep])
    return filtered, int(np.count_nonzero(~keep))


def clean_cluster_pcd(cluster_pcd, args):
    cleaned = o3d.geometry.PointCloud(cluster_pcd)
    report = {
        "raw_points": len(cleaned.points),
        "after_statistical_points": None,
        "after_radius_points": None,
        "post_clean_component_count": None,
        "post_clean_component_label": None,
        "clean_points": None,
    }

    if not args.disable_statistical_filter and len(cleaned.points) >= args.stat_nb_neighbors + 1:
        cleaned, _ = cleaned.remove_statistical_outlier(
            nb_neighbors=args.stat_nb_neighbors,
            std_ratio=args.stat_std_ratio,
        )
        report["after_statistical_points"] = len(cleaned.points)

    if not args.disable_radius_filter and len(cleaned.points) >= args.radius_nb_points:
        cleaned, _ = cleaned.remove_radius_outlier(
            nb_points=args.radius_nb_points,
            radius=args.radius,
        )
        report["after_radius_points"] = len(cleaned.points)

    if args.post_clean_cluster_eps > 0 and len(cleaned.points) >= args.post_clean_cluster_min_points:
        labels = np.asarray(
            cleaned.cluster_dbscan(
                eps=args.post_clean_cluster_eps,
                min_points=args.post_clean_cluster_min_points,
                print_progress=False,
            )
        )
        valid_labels = [label for label in sorted(set(labels.tolist())) if label >= 0]
        report["post_clean_component_count"] = len(valid_labels)
        if valid_labels:
            largest_label = max(valid_labels, key=lambda label: int(np.count_nonzero(labels == label)))
            keep_idx = np.where(labels == largest_label)[0]
            cleaned = cleaned.select_by_index(keep_idx)
            report["post_clean_component_label"] = int(largest_label)

    report["clean_points"] = len(cleaned.points)
    return cleaned, report


def format_extent(points):
    if len(points) == 0:
        return [0.0, 0.0, 0.0]
    return [float(v) for v in np.ptp(points, axis=0)]


def save_depth_debug_images(output_dir, ts, frames, valid_mask, edge_mask):
    color_path = output_dir / f"{ts}_color.png"
    valid_path = output_dir / f"{ts}_depth_valid_mask.png"
    edge_path = output_dir / f"{ts}_depth_edge_rejected_mask.png"

    cv2.imwrite(str(color_path), frames.color_bgr)
    cv2.imwrite(str(valid_path), np.uint8(valid_mask) * 255)
    cv2.imwrite(str(edge_path), np.uint8(edge_mask) * 255)


def save_outputs(output_dir, ts, pcd_base_crop, pcd_no_table, cluster_records, metadata, frames, valid_mask, edge_mask):
    output_dir.mkdir(parents=True, exist_ok=True)
    o3d.io.write_point_cloud(str(output_dir / f"{ts}_pcd_base_crop_workspace.ply"), pcd_base_crop)
    o3d.io.write_point_cloud(str(output_dir / f"{ts}_pcd_base_no_table.ply"), pcd_no_table)

    for record in cluster_records:
        label = record["label"]
        o3d.io.write_point_cloud(str(output_dir / f"{ts}_cluster_label_{label:02d}_raw.ply"), record["raw_pcd"])
        o3d.io.write_point_cloud(str(output_dir / f"{ts}_cluster_label_{label:02d}_clean.ply"), record["clean_pcd"])

    save_depth_debug_images(output_dir, ts, frames, valid_mask, edge_mask)

    metadata_path = output_dir / f"{ts}_metadata.json"
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"\nSaved cleaned point-cloud debug outputs to: {output_dir}")
    print(f"Metadata: {metadata_path}")


def detect_and_clean(args):
    T_base_marker = load_T_base_marker(args.calibration)
    workspace = load_table_workspace(args.table_workspace)

    detector_bundle = create_aruco_detector()
    camera = RealSenseCamera(
        width=args.width,
        height=args.height,
        fps=args.fps,
        stream_order=args.camera_stream_order,
    )

    print("\n========== Real Clean Cup PointCloud Test ==========")
    print("Perception only: no Kortex connection and no robot motion.")
    print(f"MARKER_LENGTH={MARKER_LENGTH:.3f} m, target marker ID={TARGET_MARKER_ID}")
    print(f"Using table workspace: {workspace['path']}")
    print(f"workspace z: [{workspace['z_min']:.3f}, {workspace['z_max']:.3f}]")
    print(
        "Depth edge filter: "
        f"{'off' if args.disable_depth_edge_filter else 'on'}, "
        f"threshold={args.depth_edge_threshold:.3f} m, kernel={args.depth_edge_kernel}"
    )

    try:
        camera.start(
            start_attempts=args.camera_start_attempts,
            retry_delay_s=args.camera_retry_delay,
            hardware_reset_on_fail=args.camera_hardware_reset_on_fail,
        )

        frames = None
        marker_detection = None
        for attempt in range(120):
            frames = camera.get_aligned_frames()
            if frames is None:
                continue
            marker_detection, corners, ids, rejected = detect_target_marker_pose(
                frames.color_bgr,
                frames.camera_matrix,
                frames.dist_coeffs,
                detector_bundle=detector_bundle,
            )
            if marker_detection is not None:
                break
            if attempt % 20 == 0:
                print(f"Waiting for marker ID {TARGET_MARKER_ID}... attempt {attempt}")

        if frames is None or marker_detection is None:
            raise RuntimeError(f"Could not detect ArUco marker ID {TARGET_MARKER_ID}.")

        valid_mask, edge_mask, depth_m = make_depth_valid_mask(frames.depth_z16, frames.depth_scale_m, args)
        T_base_camera = T_base_marker @ invert_T(marker_detection.T_camera_marker)

        pcd_camera = build_camera_point_cloud(frames, valid_mask, args)
        pcd_base_full = transform_pcd(pcd_camera, T_base_camera)
        pcd_base_crop = crop_pcd_by_workspace(pcd_base_full, workspace)
        pcd_no_table, plane_model, inliers = remove_table_plane(pcd_base_crop, args)
        pcd_no_table, near_table_removed = remove_near_table_residuals(pcd_no_table, plane_model, args)

        print(f"\nDepth valid pixels after filtering: {int(np.count_nonzero(valid_mask))}")
        print(f"Depth edge rejected pixels: {int(np.count_nonzero(edge_mask))}")
        print(f"Workspace points: {len(pcd_base_crop.points)}")
        print(f"Table plane model: {plane_model}")
        print(f"Table inliers: {len(inliers)}")
        print(f"Near-table residual points removed: {near_table_removed}")
        print(f"Non-table points: {len(pcd_no_table.points)}")

        if len(pcd_no_table.points) < args.cluster_min_points:
            raise RuntimeError("Not enough non-table points after plane removal.")

        labels = np.asarray(
            pcd_no_table.cluster_dbscan(
                eps=args.cluster_eps,
                min_points=args.cluster_min_points,
                print_progress=False,
            )
        )
        if labels.size == 0 or labels.max() < 0:
            raise RuntimeError("DBSCAN found no clusters. Try increasing --cluster-eps or reducing --cluster-min-points.")

        total_clustered_points = int(labels.size)
        noise_points = int(np.count_nonzero(labels < 0))
        cluster_labels = [int(label) for label in sorted(set(labels.tolist())) if label >= 0]
        print("\nDBSCAN summary:")
        print(f"total non-table input points: {total_clustered_points}")
        print(f"noise points(label=-1): {noise_points}")
        print(f"cluster count: {len(cluster_labels)}")

        cluster_records = []
        metadata_clusters = []
        print("\nClusters:")
        for label in cluster_labels:
            idx = np.where(labels == label)[0]
            raw_count_before_min_filter = int(len(idx))
            if len(idx) < args.min_points:
                print(
                    f"label={label:02d}, points={raw_count_before_min_filter} "
                    f"< min_points={args.min_points}, skipped"
                )
                continue

            raw_pcd = pcd_no_table.select_by_index(idx)
            clean_pcd, clean_report = clean_cluster_pcd(raw_pcd, args)
            raw_points = np.asarray(raw_pcd.points)
            clean_points = np.asarray(clean_pcd.points)

            raw_extent = format_extent(raw_points)
            clean_extent = format_extent(clean_points)
            clean_ratio = (
                float(clean_report["clean_points"] / clean_report["raw_points"])
                if clean_report["raw_points"] > 0
                else 0.0
            )

            print(
                f"label={label:02d}, "
                f"raw_points={clean_report['raw_points']}, "
                f"after_stat={clean_report['after_statistical_points']}, "
                f"after_radius={clean_report['after_radius_points']}, "
                f"components={clean_report['post_clean_component_count']}, "
                f"clean_points={clean_report['clean_points']}, "
                f"clean_ratio={clean_ratio:.2f}, "
                f"raw_extent={[round(v, 4) for v in raw_extent]}, "
                f"clean_extent={[round(v, 4) for v in clean_extent]}"
            )

            cluster_records.append(
                {
                    "label": int(label),
                    "raw_pcd": raw_pcd,
                    "clean_pcd": clean_pcd,
                }
            )
            metadata_clusters.append(
                {
                    "label": int(label),
                    **clean_report,
                    "clean_ratio": clean_ratio,
                    "raw_extent": raw_extent,
                    "clean_extent": clean_extent,
                }
            )

        if not cluster_records:
            raise RuntimeError(f"No cluster has at least --min-points={args.min_points}.")

        ts = time.strftime("%Y%m%d_%H%M%S")
        metadata = {
            "timestamp": ts,
            "table_workspace": str(workspace["path"]),
            "depth_valid_pixels": int(np.count_nonzero(valid_mask)),
            "depth_edge_rejected_pixels": int(np.count_nonzero(edge_mask)),
            "workspace_points": len(pcd_base_crop.points),
            "non_table_points": len(pcd_no_table.points),
            "near_table_residual_points_removed": near_table_removed,
            "dbscan_total_input_points": total_clustered_points,
            "dbscan_noise_points": noise_points,
            "dbscan_cluster_count": len(cluster_labels),
            "table_plane_model": None if plane_model is None else [float(v) for v in plane_model],
            "parameters": {
                "depth_min": args.depth_min,
                "depth_trunc": args.depth_trunc,
                "voxel_size": args.voxel_size,
                "depth_edge_filter": not args.disable_depth_edge_filter,
                "depth_edge_threshold": args.depth_edge_threshold,
                "depth_edge_kernel": args.depth_edge_kernel,
                "table_distance_threshold": args.table_distance_threshold,
                "near_table_filter": not args.disable_near_table_filter,
                "near_table_clearance": args.near_table_clearance,
                "cluster_eps": args.cluster_eps,
                "cluster_min_points": args.cluster_min_points,
                "min_points": args.min_points,
                "statistical_filter": not args.disable_statistical_filter,
                "stat_nb_neighbors": args.stat_nb_neighbors,
                "stat_std_ratio": args.stat_std_ratio,
                "radius_filter": not args.disable_radius_filter,
                "radius_nb_points": args.radius_nb_points,
                "radius": args.radius,
                "post_clean_cluster_eps": args.post_clean_cluster_eps,
                "post_clean_cluster_min_points": args.post_clean_cluster_min_points,
            },
            "clusters": metadata_clusters,
        }

        save_outputs(
            args.output_dir,
            ts,
            pcd_base_crop,
            pcd_no_table,
            cluster_records,
            metadata,
            frames,
            valid_mask,
            edge_mask,
        )

        return cluster_records, metadata

    finally:
        camera.stop()


def main():
    args = parse_args()
    detect_and_clean(args)


if __name__ == "__main__":
    main()
