#!/usr/bin/env python3
"""Detect cup/object principal axes inside the calibrated table workspace.

中文说明：在校准好的桌面区域内检测杯子或物体点云 cluster，并用 PCA 估计主轴。
该脚本只做感知，不移动 Kinova 机械臂。

This script is perception-only and does not move the Kinova arm.

Pipeline:
1. Capture one aligned RealSense RGB-D frame.
2. Detect ArUco marker ID 23 and compute T_base_camera.
3. Build a base-frame point cloud.
4. Crop points by configs/table_workspace.yaml.
5. Remove the table plane.
6. DBSCAN cluster remaining objects.
7. Run PCA on each cluster and classify its main axis as upright/lying/unknown.
"""

from __future__ import annotations

import argparse
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import open3d as o3d
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from perception.aruco_detector import (  # noqa: E402
    MARKER_LENGTH,
    TARGET_MARKER_ID,
    create_aruco_detector,
    detect_target_marker_pose,
)
from perception.realsense_camera import RealSenseCamera  # noqa: E402
from utils.transform_utils import invert_T  # noqa: E402


@dataclass
class AxisCandidate:
    label: int
    num_points: int
    center_base: np.ndarray
    extent: np.ndarray
    principal_axis: np.ndarray
    eigenvalues: np.ndarray
    axis_confidence: float
    axis_z_abs: float
    state: str
    reason: str


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--fps", type=int, default=15)
    parser.add_argument(
        "--camera-stream-order",
        choices=["color_first", "depth_first", "both"],
        default="color_first",
    )
    parser.add_argument("--camera-start-attempts", type=int, default=3)
    parser.add_argument("--camera-retry-delay", type=float, default=2.0)
    parser.add_argument(
        "--camera-hardware-reset-on-fail",
        action="store_true",
        help="Request a RealSense hardware reset before retrying after the first startup failure.",
    )

    parser.add_argument(
        "--calibration",
        type=Path,
        default=PROJECT_ROOT / "configs" / "real_calibration.yaml",
        help="YAML file containing T_base_marker.",
    )
    parser.add_argument(
        "--table-workspace",
        type=Path,
        default=PROJECT_ROOT / "configs" / "table_workspace.yaml",
        help="YAML generated by scripts/calibrate_table_workspace.py.",
    )

    parser.add_argument("--depth-trunc", type=float, default=1.20)
    parser.add_argument("--voxel-size", type=float, default=0.004)
    parser.add_argument("--table-distance-threshold", type=float, default=0.008)
    parser.add_argument("--cluster-eps", type=float, default=0.03)
    parser.add_argument("--cluster-min-points", type=int, default=50)
    parser.add_argument("--min-points", type=int, default=80)

    parser.add_argument(
        "--min-axis-confidence",
        type=float,
        default=1.15,
        help="Minimum lambda1/lambda2 ratio required to trust the PCA main axis.",
    )
    parser.add_argument(
        "--upright-axis-z",
        type=float,
        default=0.75,
        help="abs(dot(axis, base_z)) above this means upright.",
    )
    parser.add_argument(
        "--lying-axis-z",
        type=float,
        default=0.35,
        help="abs(dot(axis, base_z)) below this means lying.",
    )
    parser.add_argument(
        "--select-strategy",
        choices=["largest", "nearest", "highest-confidence"],
        default="largest",
        help="Which cluster to print again as Selected target.",
    )
    parser.add_argument(
        "--save-debug-pcd",
        action="store_true",
        help="Save cropped/no-table/cluster point clouds under debug_pointclouds/cup_axis/.",
    )
    return parser.parse_args()


def load_T_base_marker(path: Path) -> np.ndarray:
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    T_base_marker = np.asarray(data["T_base_marker"], dtype=np.float64)
    if T_base_marker.shape != (4, 4):
        raise ValueError("T_base_marker must be 4x4.")
    return T_base_marker


def load_table_workspace(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"Missing table workspace file: {path}\n"
            "Run: python scripts/calibrate_table_workspace.py"
        )
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    workspace = data.get("table_workspace", data)
    polygon = np.asarray(workspace["polygon_base_xy"], dtype=np.float64)
    if polygon.ndim != 2 or polygon.shape[1] != 2 or polygon.shape[0] < 3:
        raise ValueError("polygon_base_xy must be an Nx2 polygon with at least three points.")
    return {
        "polygon_base_xy": polygon,
        "z_min": float(workspace["z_min"]),
        "z_max": float(workspace["z_max"]),
        "path": path,
    }


def points_in_polygon_xy(points_xy, polygon_xy):
    polygon = np.asarray(polygon_xy, dtype=np.float32).reshape(-1, 1, 2)
    return np.array(
        [cv2.pointPolygonTest(polygon, (float(p[0]), float(p[1])), False) >= 0 for p in points_xy],
        dtype=bool,
    )


def build_camera_point_cloud(frames, args):
    depth_m = frames.depth_z16.astype(np.float64) * float(frames.depth_scale_m)
    h, w = depth_m.shape

    us, vs = np.meshgrid(np.arange(w), np.arange(h))
    valid = np.isfinite(depth_m) & (depth_m > 0.05) & (depth_m < args.depth_trunc)

    z = depth_m[valid]
    x = (us[valid].astype(np.float64) - frames.camera_matrix[0, 2]) * z / frames.camera_matrix[0, 0]
    y = (vs[valid].astype(np.float64) - frames.camera_matrix[1, 2]) * z / frames.camera_matrix[1, 1]
    points = np.stack([x, y, z], axis=1)

    color_rgb = cv2.cvtColor(frames.color_bgr, cv2.COLOR_BGR2RGB)
    colors = color_rgb[valid].astype(np.float64) / 255.0

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    pcd.colors = o3d.utility.Vector3dVector(colors)
    if args.voxel_size > 0:
        pcd = pcd.voxel_down_sample(args.voxel_size)
    return pcd


def transform_pcd(pcd, T_A_B):
    out = o3d.geometry.PointCloud(pcd)
    out.transform(np.asarray(T_A_B, dtype=np.float64).reshape(4, 4))
    return out


def crop_pcd_by_workspace(pcd_base_full, workspace):
    points = np.asarray(pcd_base_full.points)
    colors = np.asarray(pcd_base_full.colors)

    polygon_mask = points_in_polygon_xy(points[:, :2], workspace["polygon_base_xy"])
    z_mask = (points[:, 2] >= workspace["z_min"]) & (points[:, 2] <= workspace["z_max"])
    mask = polygon_mask & z_mask

    pcd_crop = o3d.geometry.PointCloud()
    pcd_crop.points = o3d.utility.Vector3dVector(points[mask])
    if colors.shape[0] == points.shape[0]:
        pcd_crop.colors = o3d.utility.Vector3dVector(colors[mask])
    return pcd_crop


def remove_table_plane(pcd_base_crop, args):
    if len(pcd_base_crop.points) < 100:
        return pcd_base_crop, None, []
    try:
        plane_model, inliers = pcd_base_crop.segment_plane(
            distance_threshold=args.table_distance_threshold,
            ransac_n=3,
            num_iterations=1000,
        )
        return pcd_base_crop.select_by_index(inliers, invert=True), plane_model, inliers
    except RuntimeError:
        return pcd_base_crop, None, []


def compute_pca_axis(points):
    points = np.asarray(points, dtype=np.float64)
    center = np.mean(points, axis=0)
    X = points - center
    cov = X.T @ X / max(len(points) - 1, 1)
    eigvals, eigvecs = np.linalg.eigh(cov)

    order = np.argsort(eigvals)[::-1]
    eigvals = eigvals[order]
    eigvecs = eigvecs[:, order]

    principal_axis = eigvecs[:, 0]
    principal_axis = principal_axis / max(np.linalg.norm(principal_axis), 1e-12)
    axis_confidence = float(eigvals[0] / max(eigvals[1], 1e-12))
    return center, principal_axis, eigvals, axis_confidence


def classify_axis(principal_axis, axis_confidence, args):
    axis_z_abs = abs(float(np.dot(principal_axis, np.array([0.0, 0.0, 1.0]))))
    if axis_confidence < args.min_axis_confidence:
        return "unknown", "pca_axis_not_distinct", axis_z_abs
    if axis_z_abs >= args.upright_axis_z:
        return "upright", "axis_near_base_z", axis_z_abs
    if axis_z_abs <= args.lying_axis_z:
        return "lying", "axis_near_horizontal", axis_z_abs
    return "unknown", "axis_angle_ambiguous", axis_z_abs


def make_axis_candidate(label, idx, pcd_no_table, args):
    cluster_pcd = pcd_no_table.select_by_index(idx)
    points = np.asarray(cluster_pcd.points)
    min_bound = np.min(points, axis=0)
    max_bound = np.max(points, axis=0)
    extent = max_bound - min_bound

    center, principal_axis, eigvals, axis_confidence = compute_pca_axis(points)
    state, reason, axis_z_abs = classify_axis(principal_axis, axis_confidence, args)

    return AxisCandidate(
        label=int(label),
        num_points=int(len(idx)),
        center_base=center,
        extent=extent,
        principal_axis=principal_axis,
        eigenvalues=eigvals,
        axis_confidence=axis_confidence,
        axis_z_abs=axis_z_abs,
        state=state,
        reason=reason,
    )


def select_candidate(candidates, args):
    if not candidates:
        return None
    if args.select_strategy == "nearest":
        return min(candidates, key=lambda c: float(np.linalg.norm(c.center_base[:2])))
    if args.select_strategy == "highest-confidence":
        return max(candidates, key=lambda c: c.axis_confidence)
    return max(candidates, key=lambda c: c.num_points)


def fmt_vec(vec):
    return "[" + ", ".join(f"{float(v):.4f}" for v in vec) + "]"


def print_candidate(candidate):
    print(f"label={candidate.label}")
    print(f"num_points={candidate.num_points}")
    print(f"center_base={fmt_vec(candidate.center_base)}")
    print(f"extent={fmt_vec(candidate.extent)}")
    print(f"principal_axis={fmt_vec(candidate.principal_axis)}")
    print(f"axis_z_abs={candidate.axis_z_abs:.4f}")
    print(f"axis_confidence(lambda1/lambda2)={candidate.axis_confidence:.4f}")
    print(f"eigenvalues={fmt_vec(candidate.eigenvalues)}")
    print(f"state={candidate.state}")
    print(f"reason={candidate.reason}")
    print("")


def save_debug_point_clouds(pcd_base_crop, pcd_no_table, pcd_clusters, candidates):
    debug_dir = PROJECT_ROOT / "debug_pointclouds" / "cup_axis"
    debug_dir.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d_%H%M%S")

    o3d.io.write_point_cloud(str(debug_dir / f"{ts}_pcd_base_crop_workspace.ply"), pcd_base_crop)
    o3d.io.write_point_cloud(str(debug_dir / f"{ts}_pcd_base_no_table.ply"), pcd_no_table)

    for candidate in candidates:
        cluster_pcd = pcd_clusters[candidate.label]
        filename = f"{ts}_cluster_label_{candidate.label:02d}_{candidate.state}_{candidate.reason}.ply"
        o3d.io.write_point_cloud(str(debug_dir / filename), cluster_pcd)

    print(f"Saved debug point clouds to: {debug_dir}")


def detect_axes(args):
    T_base_marker = load_T_base_marker(args.calibration)
    workspace = load_table_workspace(args.table_workspace)

    detector_bundle = create_aruco_detector()
    camera = RealSenseCamera(
        width=args.width,
        height=args.height,
        fps=args.fps,
        stream_order=args.camera_stream_order,
    )

    print("\n========== Real Cup Axis PCA Test ==========")
    print("Perception only: no Kortex connection and no robot motion.")
    print(f"MARKER_LENGTH={MARKER_LENGTH:.3f} m, target marker ID={TARGET_MARKER_ID}")
    print(f"Using table workspace: {workspace['path']}")
    print(f"workspace z: [{workspace['z_min']:.3f}, {workspace['z_max']:.3f}]")

    try:
        camera.start(
            start_attempts=args.camera_start_attempts,
            retry_delay_s=args.camera_retry_delay,
            hardware_reset_on_fail=args.camera_hardware_reset_on_fail,
        )

        frames = None
        marker_detection = None
        for attempt in range(120):
            frames = camera.get_aligned_frames()
            if frames is None:
                continue
            marker_detection, corners, ids, rejected = detect_target_marker_pose(
                frames.color_bgr,
                frames.camera_matrix,
                frames.dist_coeffs,
                detector_bundle=detector_bundle,
            )
            if marker_detection is not None:
                break
            if attempt % 20 == 0:
                print(f"Waiting for marker ID {TARGET_MARKER_ID}... attempt {attempt}")

        if frames is None or marker_detection is None:
            raise RuntimeError(f"Could not detect ArUco marker ID {TARGET_MARKER_ID}.")

        T_base_camera = T_base_marker @ invert_T(marker_detection.T_camera_marker)
        pcd_camera = build_camera_point_cloud(frames, args)
        pcd_base_full = transform_pcd(pcd_camera, T_base_camera)
        pcd_base_crop = crop_pcd_by_workspace(pcd_base_full, workspace)
        pcd_no_table, plane_model, inliers = remove_table_plane(pcd_base_crop, args)

        print(f"\nCropped workspace points: {len(pcd_base_crop.points)}")
        print(f"Table plane model: {plane_model}")
        print(f"Table inliers: {len(inliers)}")
        print(f"Non-table points: {len(pcd_no_table.points)}")

        if len(pcd_no_table.points) < args.cluster_min_points:
            raise RuntimeError("Not enough non-table points after plane removal.")

        labels = np.asarray(
            pcd_no_table.cluster_dbscan(
                eps=args.cluster_eps,
                min_points=args.cluster_min_points,
                print_progress=False,
            )
        )
        if labels.size == 0 or labels.max() < 0:
            raise RuntimeError("DBSCAN found no clusters. Try increasing --cluster-eps or reducing --cluster-min-points.")

        candidates = []
        pcd_clusters = {}
        for label in sorted(set(labels.tolist())):
            if label < 0:
                continue
            idx = np.where(labels == label)[0]
            if len(idx) < args.min_points:
                continue
            pcd_clusters[int(label)] = pcd_no_table.select_by_index(idx)
            candidates.append(make_axis_candidate(label, idx, pcd_no_table, args))

        print("\nPCA axis candidates:")
        if not candidates:
            raise RuntimeError(f"No cluster has at least --min-points={args.min_points}.")
        for candidate in candidates:
            print_candidate(candidate)

        selected = select_candidate(candidates, args)
        print("Selected target:")
        print_candidate(selected)

        if args.save_debug_pcd:
            save_debug_point_clouds(pcd_base_crop, pcd_no_table, pcd_clusters, candidates)

        return selected, candidates

    finally:
        camera.stop()


def main():
    args = parse_args()
    detect_axes(args)


if __name__ == "__main__":
    main()
